language: android
jdk: oraclejdk8
notifications:
  email:
    - external-ci-notifications+braintree-android@getbraintree.com
sudo: true
android:
  components:
    - tools
    - tools
    - platform-tools
    - build-tools-28.0.2
    - android-28
    - extra-google-m2repository
before_install:
  - yes | sdkmanager "platforms;android-28"
script: ./gradlew --stacktrace lint test
after_success: ./script/deploy_snapshot.sh
